# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='')),
                ('current_screen', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('number_of_current_user', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=50000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='myapp.Room')),
            ],
        ),
    ]
