# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'verbose_name': 'Screen', 'verbose_name_plural': 'Screens'},
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.FileField(upload_to='room_thumbnails'),
        ),
        migrations.AddField(
            model_name='roomactiveuser',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_rooms', to='myapp.Room'),
        ),
        migrations.AddField(
            model_name='roomactiveuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='roomactiveuser',
            unique_together=set([('room', 'user')]),
        ),
    ]
