# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_add_number_of_slide_field_in_room_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messsages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'verbose_name': 'Room',
            },
        ),
    ]
