# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_add_room_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='image',
            field=models.FileField(default=1, upload_to=myapp.models.get_upload_to),
            preserve_default=False,
        ),
    ]
